import type {Metadata} from "next";
import {Roboto} from 'next/font/google'
import "./globals.css";
import AntdConfigProvider from "@/components/providers/AntdConfigProvider";

const roboto = Roboto({
    weight: ['100', '300', '400', '500', '700', '900'],
    subsets: ['latin'],
    display: 'swap',
})

export const metadata: Metadata = {
    title: "VissSoft Test - Nguyen Quang Hung",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={roboto.className}>
        <body>
        <AntdConfigProvider>
            {children}
        </AntdConfigProvider>
        </body>
        </html>
    );
}
